// <auto-generated />
using System;
using ADO.NET;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ADO.NET.Migrations
{
    [DbContext(typeof(MyAppContext))]
    [Migration("20250406094357_UpdateMedicine")]
    partial class UpdateMedicine
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ADO.NET.Entities.Cashier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("CashierId");

                    b.Property<string>("CashierName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CashierName");

                    b.Property<long>("CashierPohneNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("CashierPhoneNumber");

                    b.HasKey("Id");

                    b.ToTable("Cashier");
                });

            modelBuilder.Entity("ADO.NET.Entities.CashierMedicine", b =>
                {
                    b.Property<Guid>("CashierMedicineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CashierId")
                        .HasColumnType("uuid")
                        .HasColumnName("CashierId");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid")
                        .HasColumnName("MedicineId");

                    b.HasKey("CashierMedicineId");

                    b.HasIndex("CashierId");

                    b.HasIndex("MedicineId");

                    b.ToTable("CashierMedicine");
                });

            modelBuilder.Entity("ADO.NET.Entities.Medicine", b =>
                {
                    b.Property<Guid>("MedicineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("CashierId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("MedicineId1")
                        .HasColumnType("uuid");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("Price")
                        .IsRequired()
                        .HasColumnType("numeric");

                    b.HasKey("MedicineId");

                    b.HasIndex("CashierId");

                    b.HasIndex("MedicineId1");

                    b.ToTable("Medicine");
                });

            modelBuilder.Entity("ADO.NET.Entities.CashierMedicine", b =>
                {
                    b.HasOne("ADO.NET.Entities.Cashier", "Cashier")
                        .WithMany("CashiersMedicines")
                        .HasForeignKey("CashierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ADO.NET.Entities.Medicine", "Medicine")
                        .WithMany("CashierMedicines")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cashier");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("ADO.NET.Entities.Medicine", b =>
                {
                    b.HasOne("ADO.NET.Entities.Cashier", null)
                        .WithMany("Medicines")
                        .HasForeignKey("CashierId");

                    b.HasOne("ADO.NET.Entities.Medicine", null)
                        .WithMany("Cashiers")
                        .HasForeignKey("MedicineId1");
                });

            modelBuilder.Entity("ADO.NET.Entities.Cashier", b =>
                {
                    b.Navigation("CashiersMedicines");

                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("ADO.NET.Entities.Medicine", b =>
                {
                    b.Navigation("CashierMedicines");

                    b.Navigation("Cashiers");
                });
#pragma warning restore 612, 618
        }
    }
}
